import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.44.0'
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Define the expected BYOD event shape
interface BYODEvent {
  headline: string;
  latitude: number;
  longitude: number;
  severity?: number; // 1 to 10
  event_type?: string;
  occurred_at?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Missing Authorization header');
    }

    // Create a Supabase client with the Auth context of the user making the request
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {
        global: {
          headers: { Authorization: authHeader },
        },
      }
    )

    // Verify the user's JWT to get their organization ID
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser()
    
    if (userError || !user) {
      console.error('Auth error:', userError);
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // For the hackathon, we assume the organization_id is mocked or retrieved from user_roles
    // Fallback to a mock 'sentinel_org' if not present in JWT for testing
    let organizationId = user.app_metadata?.organization_id;
    if (!organizationId) {
      // Look it up from profiles or just use a default test tenant
      organizationId = "00000000-0000-0000-0000-000000000001"; // Mock UUID for testing
    }

    const body = await req.json();
    const events: BYODEvent[] = Array.isArray(body) ? body : [body];

    if (events.length === 0) {
      return new Response(JSON.stringify({ error: 'No events provided' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Transform BYOD events into the Sentinel schema
    const sentinelEvents = events.map(event => ({
      gdelt_id: `BYOD-${crypto.randomUUID()}`, // Use a generated BYOD id
      headline: event.headline,
      latitude: event.latitude,
      longitude: event.longitude,
      severity: event.severity || 5,
      event_type: event.event_type || 'custom_internal_event',
      occurred_at: event.occurred_at || new Date().toISOString(),
      organization_id: organizationId,
      is_proprietary: true
    }));

    // Insert into Supabase
    // Because we are using the user's auth token, RLS will enforce they can insert (if we allowed it)
    // But since this is a secure edge function, we might want to bypass RLS to ensure fast ingestion 
    // using the service_role key, while explicitly setting the organization_id from the verified user token.
    
    const adminClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const { data, error } = await adminClient
      .from('sentinel_events')
      .insert(sentinelEvents)
      .select();

    if (error) {
      console.error('Database error:', error);
      throw new Error(`Failed to ingest events: ${error.message}`);
    }

    return new Response(
      JSON.stringify({
        message: `Successfully ingested ${data.length} proprietary events.`,
        ingested_count: data.length,
        organization_id: organizationId
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    )

  } catch (error) {
    console.error('Ingestion error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    })
  }
})
