// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = (import.meta as any).env.VITE_SUPABASE_URL || "https://bmnrwukxkskdazwrralw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env.VITE_SUPABASE_PUBLISHABLE_KEY || (import.meta as any).env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbnJ3dWt4a3NrZGF6d3JyYWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMzNTI1NzIsImV4cCI6MjA5ODkyODU3Mn0.m318rw9rXhaC8Zi-kWwnd7NJDl1Awvl5kSgbdB0Bc5s";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // auth defaults (persistSession: true, autoRefreshToken: true) are used
  global: {
    fetch: (url, options) => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000); // 30s Circuit Breaker
      return fetch(url, { ...options, signal: controller.signal })
        .then(response => {
          clearTimeout(timeoutId);
          return response;
        })
        .catch(error => {
          clearTimeout(timeoutId);
          throw error;
        });
    }
  }
});